version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meorganiza-frontend
    ports:
      - "81:80"
    environment:
      VITE_API_BASE_URL: "${VITE_API_BASE_URL}"
